### ISSUE TITLE
Unnecessary ParenthesizedExpression are added

### ISSUE THREAD

**Issue by diontools** [wessberg/ts-clone-node#1]
Hello. I noticed that the cloneNode adds parenthesis that is not in the source.

[reproduction code](https://codesandbox.io/s/ts-clone-node-paren-inserted-6h7nk)

input:
```ts
({
    foo: undefined as any,
});
```

output:
```ts
({ foo: (undefined as any) });
```

I want to preserve the `multiLine` of Block and ObjectLiteral, and I have the following code.

```ts
function preserveMultiLine(node: ts.Node, sourceNode: ts.Node) {
    if ((sourceNode as any).multiLine) {
        (node as any).multiLine = (sourceNode as any).multiLine
    }

    const children: ts.Node[] = []
    node.forEachChild(child => { children.push(child) })

    const sourceChildren: ts.Node[] = []
    sourceNode.forEachChild(child => { sourceChildren.push(child) })

    for (let i = 0; i < children.length; i++) {
        preserveMultiLine(children[i], sourceChildren[i])
    }
}

const source = ...
const clone = cloneNode(source)
preserveMultiLine(clone, source)
```

However, this doesn't work because it adds unnecessary parenthesis in the cloneNode.
Is there any way to prevent the addition of parenthesis?

**Comment by wessberg** [comment]
Hey there. Thanks for submitting this issue. This is due to how TypeScript's internals work when using the `createPropertyAssignment` factory method:

<img width="1112" alt="Screen Shot 2020-08-07 at 23 50 12" src="https://user-images.githubusercontent.com/20454213/89691722-f2395c80-d909-11ea-8eb6-c2f18d585b25.png">

It may add parentheses where based on precedence rules.

I've added a workaround that checks if parentheses were added that weren't part of the source node, and if so, they will be discarded.

This has been released as part of [v0.3.12](https://github.com/wessberg/ts-clone-node/releases/tag/v0.3.12)

**Comment by diontools** [comment]
Thank you for your response.
It looks like parentheses will be added to the other Nodes as well.

ex.
```ts
foo(undefined as any)
const foo = undefined as any
```

I've worked around it by skipping parenthesises on the user side.

```ts
function preserveMultiLine(node: ts.Node, sourceNode: ts.Node) {
    // skip auto parenthesis
    if (ts.isParenthesizedExpression(node) && !ts.isParenthesizedExpression(sourceNode)) {
        node = node.expression
    }

    if ((sourceNode as any).multiLine) {
        (node as any).multiLine = (sourceNode as any).multiLine
    }

    const children: ts.Node[] = []
    node.forEachChild(child => { children.push(child) })

    const sourceChildren: ts.Node[] = []
    sourceNode.forEachChild(child => { sourceChildren.push(child) })

    for (let i = 0; i < children.length; i++) {
        preserveMultiLine(children[i], sourceChildren[i])
    }
}
```

**Comment by wessberg** [comment]
Nice catch. I've also added handling for this in the logic for cloning `CallExpressions` and `VariableDeclarations` and [released a new version](https://github.com/wessberg/ts-clone-node/releases/tag/v0.3.13). If you find more problems like this, please update this comment, and I'll make sure to fix them.
